name: Spring Actions Github Demo
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Starting building application"
      - name: Setup OpenJDK
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: Maven clean
        run: mvn --batch-mode --update-snapshots clean install
  package:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Start packaging application"
      - name: Package application
        run: mvn --batch-mode --update-snapshots package